## Python Basics

- Python ditemukan **Guido Van Rossum**
- General purpose : build anything
- Open source ! Free
- Dapat digunakan untuk perhitungan seperti   tambah, kurang, kali, bagi, modulus, eksponensial, dsb.

### Calculator

In [1]:
#subtraction 
print(7 - 3)
print(5 - 2)

4
3


In [2]:
#multiplication 
print(800 * 40000)

32000000


In [7]:
#division
print(80000 / 40)

2000.0


In [4]:
#modulo 
print(1920 % 3)

0


In [5]:
#exponentiation
print(15 ** 2)

225


Contoh kasus: 
Misalnya kamu punya uang 100 dollar. Diinvestasikan dengan bunga sebesar 10 % tiap tahun. Jika setelah 1 tahun uang kamu jadi 100 * 1.1 = 110 dollar, kemudian setelah 2 tahun uang kamu jadi 100 * 1.1 * 1.1 = 121 dollar. Maka setelah 7 tahun uang kamu jadi berapa ???

In [6]:
#Penyelesaian
print(100 * (1.1 ** 7))

194.87171000000012


### Variable

- Spesific
- Case-sensitive through variable name

In [7]:
height = 1.79 
weight = 74.2

In [8]:
68.7 / 1.79 ** 2

21.44127836209856

In [9]:
weight / height ** 2

23.157829031553323

In [10]:
#store in new variable 
bmi = weight / height ** 2
print(bmi)

23.157829031553323


### Type

- Tipe data dalam python ada : int, float, string, dsb
- Tipe data string tidak dapat dijumlahkan   dengan tipe data lainnya, maka dari itu     data lainnya tersebut harus dikonversi   terlebih dahulu.

In [8]:
a = 2 + 3
type(a)
#type() digunakan untuk mengetahui tipe data 

int

In [9]:
c = 'ab' + 'cd'
type(c)

str

In [1]:
savings = 100
growth_multiplier = 1.1
desc = "compound interest"

In [2]:
year1 = savings * growth_multiplier

In [3]:
year1

110.00000000000001

In [4]:
doubledesc = desc + desc
doubledesc

'compound interestcompound interest'

In [1]:
# Type conversion 
savings = 100
result = 100 * 1.10 ** 7

print("I started with $" + savings + " and now have $" + result + ".Awesome!")

TypeError: can only concatenate str (not "int") to str

Code diatas error karena **strings tidak bisa digabungkan dengan tipe data lain seperti int dan float** , maka dari itu tipe data dari variable savings dan result harus di **conversi**.

In [4]:
savings = 100
result = 100 * 1.10 ** 7

print("I started with $", str(savings), "and now have $", str(result), ". Awesome!")

I started with $ 100 and now have $ 194.87171000000012 . Awesome!


In [18]:
"I can add integers, like " + str(5) + " to strings."

'I can add integers, like 5 to strings.'

## Python Lists

Python data types : 
- float - real numbers
- int - integer numbers
- str - string, text
- bool - True, False

---------------------------------------------------------------
List = [a, b, c]
- List dapat mengandung tipe data apapun bahkan mengandung list juga didalamnya

### Create a list

In [7]:
hall = 11.25
kit = 18.0
liv = 20.0
bed = 10.75
bath = 9.50

In [8]:
areas = [hall, kit, liv, bed, bath]

In [9]:
areas

[11.25, 18.0, 20.0, 10.75, 9.5]

In [10]:
areas = ["hallway", hall, "kitchen", kit, "living room", liv, "bedroom", bed, "bathroom", bath]

In [11]:
areas

['hallway',
 11.25,
 'kitchen',
 18.0,
 'living room',
 20.0,
 'bedroom',
 10.75,
 'bathroom',
 9.5]

### List of lists (list dalam list)

In [12]:
house = [["hallway", hall], 
         ["kitchen", kit], 
         ["living room", liv], 
         ["bedroom", bed],
         ["bathroom", bath]]

In [13]:
house

[['hallway', 11.25],
 ['kitchen', 18.0],
 ['living room', 20.0],
 ['bedroom', 10.75],
 ['bathroom', 9.5]]

In [14]:
type(house)

list

### Subsetting Lists

Element pertama dalam list mempunyai index 0
Element kedua dalam list mempunyai index 1 
dst

In [15]:
house

[['hallway', 11.25],
 ['kitchen', 18.0],
 ['living room', 20.0],
 ['bedroom', 10.75],
 ['bathroom', 9.5]]

[start : end]

In [16]:
house[0]
#ngambil data list yang pertama

['hallway', 11.25]

In [17]:
house[-1]
#ngambil data list yang paling akhir

['bathroom', 9.5]

In [18]:
house[0:2]
#ngambil data list dari index 0 - 1

[['hallway', 11.25], ['kitchen', 18.0]]

In [19]:
house[:3]
#ngambil 3 data pertama, index 0-2

[['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0]]

In [35]:
house[2:]
#ngambil data dari index 2 sampai akhir 

[['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]

### Slicing and dicing 

In [36]:
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

In [37]:
#Print 6 element pertama list , index 0 - 5
areas[:6]

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]

In [38]:
# Print 4 element terakhir list, index 6 - akhir
areas[6:]

['bedroom', 10.75, 'bathroom', 9.5]

### Manipulating lists

- Change list element
- Add list elements
- Remove list elements

In [20]:
fam = ["Liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89]

In [21]:
fam

['Liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89]

In [22]:
#Changing list elements
fam[7] = 1.86
fam

['Liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.86]

In [23]:
fam[0:2] = ["lis", 1.74]
fam

['lis', 1.74, 'emma', 1.68, 'mom', 1.71, 'dad', 1.86]

#### Adding and removing elements

In [24]:
fam + ["me", 1.79]

['lis', 1.74, 'emma', 1.68, 'mom', 1.71, 'dad', 1.86, 'me', 1.79]

In [25]:
fam_ext = fam + ["me", 1.79]

Removing

In [26]:
del(fam[2])

In [27]:
fam

['lis', 1.74, 1.68, 'mom', 1.71, 'dad', 1.86]

In [47]:
x = ["a", "b", "c"]
y = x

In [48]:
y

['a', 'b', 'c']

In [49]:
y[1] = "z"

In [50]:
y

['a', 'z', 'c']

In [51]:
x

['a', 'z', 'c']

In [28]:
#Copy value, bukan sekalian reference 
x = ["a", "b", "c"]
y = list(x)
y = x[:]

In [53]:
y

['a', 'b', 'c']

In [54]:
y[1] = "i"

In [55]:
y 

['a', 'i', 'c']

In [29]:
x

['a', 'b', 'c']

#### Replace list elements

In [56]:
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

In [57]:
areas[-1] = 10.50
areas[-6] = "chill zone"

In [58]:
areas

['hallway',
 11.25,
 'kitchen',
 18.0,
 'chill zone',
 20.0,
 'bedroom',
 10.75,
 'bathroom',
 10.5]

#### Extend a list

In [ ]:
#Add poolhouse data to areas
areas_1 = areas + ["poolhouse", 24.5]

In [ ]:
# Add garage data to areas
areas_2 = areas_1 + ["garage", 15.45]

In [ ]:
areas_2

## Functions and Packages

### Functions

- Nothing new !
- type() merupakan salah satu function 
- piece of reusable code
- call function instead writing code yourself
- built-in function = function yang sudah disediakan python

In [30]:
fam = [1.73, 1.68, 1.71, 1.89]
fam

[1.73, 1.68, 1.71, 1.89]

In [31]:
max(fam)
#mencari nilai tertinggi dalam list

1.89

In [32]:
tallest = max(fam)
tallest

1.89

In [33]:
round(1.68, 1)
#membulatkan angka menjadi 1 angka dibelakang coma

1.7

In [34]:
round(1.51)
#otomatis membulatkan bilangan ke integer terdekat

2

In [35]:
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



In [36]:
var1 = [1, 2, 3, 4]
var2 = True

In [37]:
print(type(var1))

<class 'list'>


In [38]:
print(len(var1))
#

4


In [68]:
out2 = int(var2)

In [ ]:
print(type(out2))

In [ ]:
help(complex)

#### Multiple Arguments

In [39]:
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]

In [40]:
full = first + second 
full

[11.25, 18.0, 20.0, 10.75, 9.5]

In [ ]:
full_sorted = sorted(full, key=None, reverse=True)
#Fungsi sorted digunakan untuk mengurutkan. 
#Parameter reverse= True digunakan untuk mengurutkan dari yang terbesar ke terkecil

In [ ]:
full_sorted

### Methods

sister = "liz"
"liz" merupakan object yang bertipe data str.

Method : Functions that belong to objects

object yang bertipe data juga mempunyai methods.

- str   - capitalize(), replace().
- float - bit_length(), conjugate().
- list  - index(), count()

- Everything = object 
- Object memiliki methods yang berhubungan, tergantung pada tipe data

In [26]:
fam

[1.73, 1.68, 1.71, 1.89]

In [27]:
fam.index(1.68)

1

In [28]:
fam.count(1.71)

1

#### str methods

In [29]:
sister = "Lis"

In [30]:
sister.capitalize()

'Lis'

In [31]:
sister.replace("s", "z")

'Liz'

In [ ]:
fam = ['lis', 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89]

In [ ]:
fam.append("me")
#menambahkan element baru ke list

In [ ]:
fam

In [ ]:
fam.append(1.65)

In [ ]:
fam

In [ ]:
place = "poolhouse"

In [ ]:
place_up = place.upper()
#digunakan untuk merubah string menjadi uppercase
place_up

In [ ]:
print(place.count('o'))

#### List methods

In [ ]:
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

In [ ]:
print(areas.index(20.0))
#print dimana element 20.0 berada

In [ ]:
print(areas.count(9.50))
#menghitung seberapa banyak 9.50 muncul dalam list

In [ ]:
areas.append(24.5)
areas.append(15.45)

In [ ]:
areas

In [ ]:
areas.reverse()
#membalikkan urutan list

In [ ]:
areas

### Packages

pkg/
- mod1.py
- mod2.py

- Directory of python scripts
- each scipt = module 
- specify functions, methods, types 
- thousands of package available
        - numpy
        - matplotlib
        - scikit-learn

#### Import packages

In [2]:
import numpy
numpy.array([1, 2, 3])

array([1, 2, 3])

In [44]:
numpy.array([1, 2, 3])

array([1, 2, 3])

In [45]:
import numpy as np
np.array([1, 2, 3])
#array merupakan salah satu contoh function dalam package numpy

array([1, 2, 3])

In [46]:
#Hanya import array function pada numpy package
from numpy import array
array([1, 2, 3])

array([1, 2, 3])

In [47]:
import math

r = 0.43 
keliling_lingkaran = 2 * math.pi * r
luas_lingkaran = math.pi * r ** 2

In [ ]:
print("Keliling lingkaran : " + str(keliling_lingkaran))

In [ ]:
print("Luas lingkaran : " + str(luas_lingkaran))

In [49]:
from math import radians

r = 192500
phi = radians(12)
dist = r * phi

In [50]:
dist

40317.10572106901

In [52]:
from scipy.linalg import inv as my_inv

- scipy  = package
- linalg = sub-package
- inv    = function
- my_inv = alias dari inv function

## Numpy

- Alternative dari python list = Numpy Array
- Numpy array dapat digunakan untuk kalkulasi keseluruhan array
- Lebih cepat dan mudah

In [7]:
import numpy as np 

height = [1.73, 1.68, 1.71, 1.89]
np_height = np.array(height)

weight = [65.4, 63.6, 88.4, 68.7]
np_weight = np.array(weight)

In [8]:
np_height

array([1.73, 1.68, 1.71, 1.89])

In [15]:
for index,x in enumerate(np_height):
    print(index + 1, x)

1 1.73
2 1.68
3 1.71
4 1.89


In [71]:
np_weight

array([65.4, 63.6, 88.4, 68.7])

In [72]:
type(np_height)

numpy.ndarray

In [73]:
bmi = np_weight / np_height ** 2
bmi

array([21.85171573, 22.53401361, 30.23152423, 19.23238431])

Numpy array hanya bisa mengandung satu jenis tipe data, jika terdapat tipe data yang berbeda, maka akan dikonversi ke str.

In [74]:
python_list = [1, 2, 3]
numpy_array = np.array([1, 2, 3])

In [75]:
python_list + python_list

[1, 2, 3, 1, 2, 3]

In [ ]:
numpy_array + numpy_array

### Numpy subsetting

In [ ]:
bmi

In [ ]:
bmi[1]

In [ ]:
bmi > 20

In [ ]:
bmi[bmi > 20]

In [9]:
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

In [10]:
import numpy as np

np_baseball = np.array(baseball)
np_baseball

array([180, 215, 210, 210, 188, 176, 209, 200])

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv("baseball.csv")

In [ ]:
data

In [ ]:
# height is available as a regular list

# Import numpy
import numpy as np

# Create a numpy array from height_in: np_height_in
np_height_in = np.array(height_in)

# Print out np_height_in
print(np_height_in)

# Convert np_height_in to m: np_height_m
np_height_m = np_height_in * 0.0254

# Print np_height_m
print(np_height_m)

In [ ]:
# height and weight are available as regular lists

# Import numpy
import numpy as np

# Create array from height_in with metric units: np_height_m
np_height_m = np.array(height_in) * 0.0254

# Create array from weight_lb with metric units: np_weight_kg
np_weight_kg = np.array(weight_lb) * 0.453592

# Calculate the BMI: bmi
bmi = np_weight_kg / np_height_m ** 2

# Print out bmi
print(bmi)

In [ ]:
# height and weight are available as a regular lists

# Import numpy
import numpy as np

# Calculate the BMI: bmi
np_height_m = np.array(height_in) * 0.0254
np_weight_kg = np.array(weight_lb) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Create the light array
light = np.array(bmi < 21)

# Print out light
print(light)

# Print out BMIs of all baseball players whose BMI is below 21
print(bmi[bmi < 21])

In [32]:
np.array([True, 1, 2]) + np.array([3, 4, False])

array([4, 5, 2])

In [1]:
x = np.array([4, 3, 0]) + np.array([0, 2, 2])

NameError: name 'np' is not defined

In [ ]:
# height and weight are available as a regular lists

# Import numpy
import numpy as np

# Store weight and height lists as numpy arrays
np_weight_lb = np.array(weight_lb)
np_height_in = np.array(height_in)

# Print out the weight at index 50
print(np.array(np_weight_lb[50]))

# Print out sub-array of np_height_in: index 100 up to and including index 110
print(np.array(np_height_in[100: 111]))

### 2D Numpy Arrays

In [57]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79], 
                 [65.4, 59.2, 63.6, 88.4, 68.7]])
np_2d

array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ]])

In [55]:
np_2d.shape
# 2 baris 5 kolom

(2, 5)

In [36]:
np_2d[0][2]

1.71

In [37]:
np_2d[0,4]

1.79

In [56]:
np_2d[:, 1:3]
#ambil semua baris namun hanya kolom index 1-2

array([[ 1.68,  1.71],
       [59.2 , 63.6 ]])

In [39]:
np_2d[1, :]

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [40]:
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

In [41]:
np_baseball = np.array(baseball)

In [42]:
np_baseball

array([[180. ,  78.4],
       [215. , 102.7],
       [210. ,  98.5],
       [188. ,  75.2]])

In [43]:
np_baseball.shape

(4, 2)

In [ ]:
# baseball is available as a regular list of lists

# Import numpy package
import numpy as np

# Create np_baseball (2 cols)(kolom 1 = tinggi, kolom 2 = berat)
np_baseball = np.array(baseball)

# Print out the 50th row of np_baseball
print(np_baseball[49, :])

# Select the entire second column of np_baseball: np_weight_lb
np_weight_lb = np_baseball[:, 1]

# Print out height of 124th player
print(np_baseball[123, 0])

### Numpy : Basic Statistics

In [ ]:
np.mean(np_city[:, 0])
#mencari mean dari data kolom 1

np.median(np_city[:, 0])
#mencari median dari data kolom 1

np.corrcoef(np_city[:, 0], np_city[:, 1])
#mencari apakah kolom 1 dan kolom 2 berkorelasi

np.std(np_city[:, 0])
#mencari standar deviasi kolom 1

sort()
sum()

np.random.normal()

In [ ]:
# heights and positions are available as lists

# Import numpy
import numpy as np

# Convert positions and heights to numpy arrays: np_positions, np_heights
np_positions = np.array(positions)
np_heights = np.array(heights)


# Heights of the goalkeepers: gk_heights
gk_heights = np_heights[np_heights == 'GK']

# Heights of the other players: other_heights
other_heights = np_heights[np_heights != 'GK']

# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(other_heights)))

## Practice

- Teknik yang digunakan untuk subset list = Square brackets
- Method yang mengubah list jika merekea dipanggil = append(), remove(), reverse()

In [2]:
import numpy as np

x = np.random.normal()

In [4]:
p ="True"
print(type(p))

<class 'str'>


In [6]:
import numpy as np

np_2nd = np.array([[2, 3], [4, 5]])
print(np_2nd[-2, 1])

3


In [3]:
import numpy as np

store = np.array(["X", "Z", "Z", "Z"])
cost = np.array([2, 6, 5, 2])
select_cost = cost[store == "X"]
print(select_cost)

[2]


In [65]:
x = np.array([[2,3], [4,5]])
y = np.array([2, 0])

In [68]:
x.shape

(2, 2)

In [67]:
y.shape

(2,)